name: Deploy SPA

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:            ${{ secrets.AWS_REGION }}
        SPA_BUCKET:              ${{ secrets.SPA_BUCKET }}
        SPA_DISTRIBUTION_ID:     ${{ secrets.SPA_DISTRIBUTION_ID }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install root deps
      run: npm ci
      
    - name: Install frontend deps
      run: |
        cd frontend
        npm ci

    - name: Build React SPA
      env:
        VITE_REGION:             ${{ secrets.SPA_REGION }}
        VITE_USER_POOL_ID:       ${{ secrets.SPA_USER_POOL_ID }}
        VITE_USER_POOL_CLIENT_ID: ${{ secrets.SPA_USER_POOL_CLIENT_ID }}
        VITE_ID_POOL_ID:         ${{ secrets.SPA_ID_POOL_ID }}
        VITE_API_URL:           ${{ secrets.SPA_API_URL }}
        VITE_CDN_DOMAIN:       ${{ secrets.SPA_CDN_DOMAIN }}
        
      run: |
        cd frontend
        npm run build

    - name: Sync to S3
      run: |
        aws s3 sync frontend/dist/ s3://$SPA_BUCKET/ --delete

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id $SPA_DISTRIBUTION_ID \
          --paths '/*'
